### ISSUE TITLE
Docker image not building

### ISSUE THREAD

**Issue by mdozmorov** [aedin/PCAworkshop#1]
Likely because Docker URL should be lowercase only, on [this line](https://github.com/aedin/PCAworkshop/blob/39173d74700d239f9bf99968d95f5e1f923737b9/.github/workflows/basic_checks.yaml#L49).

Also, the DESCRIPTION file should have the DockerImage URL, like [here](https://github.com/waldronlab/PublicDataResources/blob/5b564c8226a827a436f9ab90f1141765550fee58/DESCRIPTION#L41).

**Comment by seandavi** [comment]
The package is not passing R cmd check due to (at least) a couple of missing packages. I dropped in a pull request #2 to address that one. In short, though, checking the package prior to git push will help identify problems and shortcut the troubleshooting somewhat. 

See, for example, the output of rcmdcheck here: 

- https://github.com/aedin/PCAworkshop/runs/875787672?check_suite_focus=true#step:9:16

**Comment by aedin** [comment]
This is passing rcmdcheck::rcmdcheck  on my computer so I think its because my dockerfile is not installing the package

**Comment by mdozmorov** [comment]
The `Rcpp.so` problem - it has been extensively discussed on Slack. The following lines in the Dockerfile should solve this:
````
RUN apt-get update && \
    apt-get install -y libglpk-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
````
Example where to put it, https://github.com/mdozmorov/HiCcompareWorkshop/blob/3079bc2037f670e26f0f37489401ccb8b96e4fa6/Dockerfile#L7

**Comment by lwaldron** [comment]
I submitted a couple PRs that might help: 

* https://github.com/aedin/PCAworkshop/pull/3 moves some dependencies from remotes to imports (because they were not formatted as GitHub packages, and they are CRAN packages) and from suggests to imports (because they are required in the vignette)
* https://github.com/aedin/PCAworkshop/pull/5 in the workflow installs dependencies using BiocManager and installs them from source using CRAN mirror

**Comment by mdozmorov** [comment]
There was an infamous `Rcpp.so` error. I've been testing locally the suggestions by @seandavi, https://github.com/seandavi/BuildABiocWorkshop2020/commit/4e4d001c63c2a0531da6260c91ff62b92214eb90 and https://github.com/seandavi/BuildABiocWorkshop2020/commit/7544afd0e5ae6aa89d8ff4f533d18f1d5621eecd in [this commit](https://github.com/mdozmorov/PCAworkshop/commit/8a57b1f6f1c1c68527d15c41fc581b344a5bc911). The `Rcpp.so` error is gone, as well as sporadically appearing corruption error. The only remaining problem is that the build process skips ‘Biobase’ and ‘BiocStyle’ packages. Running out of ideas what to do next.
````
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Error: (converted from warning) packages ‘Biobase’, ‘BiocStyle’ are not available (for R version 4.0.0)
Execution halted
The command '/bin/sh -c Rscript -e "options(repos = c(CRAN = 'https://cran.r-project.org')); devtools::install('.', dependencies=TRUE, build_vignettes=TRUE)"' returned a non-zero code: 1
````

**Comment by aedin** [comment]
I will have a look at others that are working and see if I have missed anything.

**Comment by lwaldron** [comment]
I only see miscellaneous issues now (a file `.gitignore (2)` causing a warning that stopped the workflow). See https://github.com/aedin/PCAworkshop/pull/9
